<?php

declare(strict_types=1);

namespace a9f\BetterRedirects\Cache;

/**
 * Abstract base class for generated redirect matchers.
 *
 * Subclasses are generated by RedirectMatcherGenerator and stored as PHP files
 * in the var/cache/code/better_redirects/ directory. They implement the four
 * abstract methods with compiled redirect data (flat trie + regex pattern arrays).
 *
 * @phpstan-type RedirectRow array{
 *     uid: int,
 *     pid: int,
 *     source_host: string,
 *     source_path: string,
 *     target: string,
 *     target_statuscode: int,
 *     force_https: int,
 *     keep_query_parameters: int,
 *     respect_query_parameters: int,
 *     is_regexp: int,
 *     disabled: int,
 *     starttime: int,
 *     endtime: int,
 *     hitcount: int,
 *     ...
 * }
 */
abstract class GeneratedRedirectMatcherBase
{
    /**
     * Match a request path+query against the compiled redirect data.
     *
     * Replicates the matching priority of RedirectService::matchRedirect() for a
     * single source host (without event dispatch):
     *  1. Flat redirects with query string (respect_query_parameters)
     *  2. Flat redirects via path-segment trie
     *  3. Regex redirects with query string (regexp_query_parameters)
     *  4. Regex redirects, path+query first, then path-only second pass (regexp_flat)
     *
     * @return RedirectRow|null
     */
    final public function match(string $path, string $query = ''): ?array
    {
        $path = rawurldecode($path);

        if ($query !== '') {
            $pathWithQuery = rtrim($path, '/') . '?' . ltrim($query, '?');
            $result = $this->matchFlatWithQuery($pathWithQuery);
            if ($result !== null) {
                return $result;
            }
            $pathWithQueryAndSlash = rtrim($path, '/') . '/?' . ltrim($query, '?');
            $result = $this->matchFlatWithQuery($pathWithQueryAndSlash);
            if ($result !== null) {
                return $result;
            }
        }

        $result = $this->matchTrieRoot(explode('/', trim($path, '/')));
        if ($result !== null) {
            return $result;
        }

        $regExpPath = $path;
        if ($query !== '') {
            $regExpPath .= '?' . ltrim($query, '?');
        }

        foreach ($this->matchRegexQueryParams() as $regexp => $redirects) {
            $matchResult = @preg_match((string)$regexp, $regExpPath);
            if ($matchResult > 0) {
                $r = self::firstActive($redirects);
                if ($r !== null) {
                    return $r;
                }
            }
        }

        foreach ($this->matchRegexFlat() as $regexp => $redirects) {
            $matchResult = @preg_match((string)$regexp, $regExpPath);
            if ($matchResult > 0) {
                $r = self::firstActive($redirects);
                if ($r !== null) {
                    return $r;
                }
            }
        }

        if ($query !== '') {
            foreach ($this->matchRegexFlat() as $regexp => $redirects) {
                $matchResult = @preg_match((string)$regexp, $path);
                if ($matchResult > 0) {
                    $r = self::firstActive($redirects);
                    if ($r !== null) {
                        return $r;
                    }
                }
            }
        }

        return null;
    }

    /**
     * Returns the first redirect from the list that is currently active
     * (not disabled, starttime passed, endtime not yet reached).
     *
     * The time check is performed at runtime so that redirects with
     * starttime/endtime restrictions are handled correctly even when the
     * generated PHP file is cached across time boundaries.
     *
     * Public and static so that anonymous classes in generated type files can
     * call GeneratedRedirectMatcherBase::firstActive() without a reference to
     * the main matcher instance.
     *
     * @param array<int, RedirectRow> $redirects
     * @return RedirectRow|null
     */
    public static function firstActive(array $redirects): ?array
    {
        $now = $GLOBALS['SIM_ACCESS_TIME'] ?? time();
        foreach ($redirects as $redirect) {
            if (
                !$redirect['disabled']
                && $redirect['starttime'] <= $now
                && (!$redirect['endtime'] || $redirect['endtime'] >= $now)
            ) {
                return $redirect;
            }
        }
        return null;
    }

    /**
     * Match against flat redirects that require query string comparison.
     * The $key is the normalised "path?query" or "path/?query" string.
     *
     * @return RedirectRow|null
     */
    abstract protected function matchFlatWithQuery(string $key): ?array;

    /**
     * Entry point for trie-based flat path matching.
     * $seg is the result of explode('/', trim($path, '/')).
     *
     * @param string[] $seg
     * @return RedirectRow|null
     */
    abstract protected function matchTrieRoot(array $seg): ?array;

    /**
     * Returns regexp_query_parameters patterns as [pattern => [redirect, ...], ...].
     *
     * @return array<string, array<int, RedirectRow>>
     */
    abstract protected function matchRegexQueryParams(): array;

    /**
     * Returns regexp_flat patterns as [pattern => [redirect, ...], ...].
     *
     * @return array<string, array<int, RedirectRow>>
     */
    abstract protected function matchRegexFlat(): array;
}
